### ISSUE TITLE
Add a git tag to first commit so that git-describe works for repo.

### ISSUE THREAD

**Issue by mithro** [alainmarcel/Surelog#105]
Could you add a `v0.0` tag to the first commit (0a6f1f6b56ecb98d47b523ba916628c0abf8e0f9) in this repository? This will make `git-describe` return a useful value for this repository.

```
git tag -a v0.0 0a6f1f6b56ecb98d47b523ba916628c0abf8e0f9 -m "First commit"
git push origin v0.0
git describe
```

**Comment by hzeller** [comment]
Done.
`v0.0-260-gcad7aea7`
