### ISSUE TITLE
Python API initialization takes a few 10ms; consider `-nopython` by default ?

### ISSUE THREAD

**Issue by hzeller** [alainmarcel/Surelog#169]
While profiling I noticed that the Python initialization can takes a few 10ms on startup (Used that in https://github.com/SymbiFlow/sv-tests/pull/636 to reduce runtime).

Currently, the Python API is on by default, and can be disabled with `-nopython`. Maybe it makes sense to reverse the logic (or maybe it is possible to delay initialization up to the point someone actually uses it ?)

**Comment by alaindargelas** [comment]
Surelog does not build Python by default anymore.
