### ISSUE TITLE
Faster builds with not building tests in UHDM and capnproto ?

### ISSUE THREAD

**Issue by hzeller** [alainmarcel/Surelog#170]
Right now it seems the recursive CMake file also builds the tests in the third_party/ libraries capnproto and UHDM. If we're only needing the libraries, maybe we can tell cmake not to bother building these ?

This might reduce build times, but might also help resolve https://github.com/SymbiFlow/conda-packages/issues/68

**Comment by kgugala** [comment]
it seems that passing `-DBUILD_TESTING=OFF` to cmake when creating build env disables c'n'p tests building.

This options could be probably set in UHDM CMakeLists, so we do not set it globally
