### ISSUE TITLE
Can grammar files be merged into one file

### ISSUE THREAD

**Issue by itviewer** [alainmarcel/Surelog#186]
I want to use Antlr  to write a SystemVerilog syntax highlighting plugin for an editor.
Can your grammar files be merged into one file? More specifically,
merge SV3_1aPpLexer.g4 and SV3_1aLexer.g4 to one file，
merge SV3_1aPpParser.g4 and SV3_1aParser.g4 to one file
Thanks

**Comment by alainmarcel** [comment]
It is quite impossible to merge the preprocessor and the parser for SystemVerilog. I tried that, especially with ANTLR, the runtime becomes rediculously

**Comment by alainmarcel** [comment]
To elaborate on the idea above,
You'd take the preprocessor grammar as a base line and augment it with the parser keywords you'd want to trigger specific actions on. Essentially only having one grammar.

**Comment by alainmarcel** [comment]
@itviewer, can I close this issue?
