### ISSUE TITLE
Commands used for unit tests are not supported in CMake 3.0

### ISSUE THREAD

**Issue by rkapuscik** [alainmarcel/Surelog#229]
Current minimum required CMake version is 3.0. Unit tests (which are run using ctest) are added using `add_test` command, which requires CMake 3.0.2

**Comment by rkapuscik** [comment]
Another problematic command is `list(FILTER <list> <INCLUDE|EXCLUDE> REGEX <regular_expression>)`, which was added in CMake 3.6

**Comment by alainmarcel** [comment]
I didn't face the first error since I have version 3.51 installed, but please bump up the required version to the version in travis.
I was talking about the filter command. That seems to be more advanced, and ubuntu default version I think is 3.51.
