### ISSUE TITLE
Set up kokoro CI on this repository

### ISSUE THREAD

**Issue by mithro** [alainmarcel/Surelog#280]
I have set up the Google side of this repo and @alaindargelas has given the permissions.

Need to add the in-repo config similar to https://github.com/SymbiFlow/fpga-tool-perf/pull/58

@acomodi can help you do that.

**Comment by alaindargelas** [comment]
Hi @acomodi, can I give you write access and can you take care of whatever is necessary?

**Comment by mithro** [comment]
I assume @rkapuscik (potentially with @hzeller's and @acomodi's help) will take care of this?

**Comment by mithro** [comment]
Reopening until we confirm kokoro is running successfully.

**Comment by mithro** [comment]
The latest build worked see - https://source.cloud.google.com/results/invocations/f187e378-befb-4d6a-b69f-76aef1e21db1/log
