### ISSUE TITLE
Clean up src/README.md

### ISSUE THREAD

**Issue by mithro** [alainmarcel/Surelog#304]
The file at https://github.com/alainmarcel/Surelog/blob/master/src/README.md seems to be partially markdown, partly some other weird syntax.

Would be nice if it was cleaned up to be easier to look at when viewed on GitHub (as it ends up at the bottom of the https://github.com/alainmarcel/Surelog/tree/master/src page.

**Comment by alaindargelas** [comment]
Fixed by #1190, #1191, #1192
