### ISSUE TITLE
Missing implementation of vpi_handle_by_name?

### ISSUE THREAD

**Issue by hs-apotell** [alainmarcel/Surelog#323]
Just wondering whether the implementation for `vpi_handle_by_name` is left out intentionally or is this something that was an oversight?

I could only find a default implementation in vpi_user.cpp which always returns 0.

**Comment by alaindargelas** [comment]
It is in the TODO list in the UHDM library. I'll actually add an issue there.

**Comment by alaindargelas** [comment]
Will be tracked there: https://github.com/alainmarcel/UHDM/issues/190

**Comment by hs-apotell** [comment]
I will close this issue and follow the other one. Thanks!

**Comment by alaindargelas** [comment]
This is done to the first order, it finds the objects in the immediate relations (No hierarchical name support).
