### ISSUE TITLE
Unable to provide own Python listener script

### ISSUE THREAD

**Issue by mkurc-ant** [alainmarcel/Surelog#331]
While trying to write an own python listener I've encountered actually two issues:

1. The `-pythonlistenerfile` commandline argument is parsed but its value is never actually used in the code. Besides that IMO there is a bug: there should be `i+1` instead of `i`: https://github.com/alainmarcel/Surelog/blob/19c61c6377060b0354b8f39d440c2ec7ec714cdc/src/CommandLine/CommandLineParser.cpp#L841

2. This is the part of code that loads the listener script: https://github.com/alainmarcel/Surelog/blob/19c61c6377060b0354b8f39d440c2ec7ec714cdc/src/API/PythonAPI.cpp#L178-L200

    I don't quite understand the intention: It looks like the code is supposed to look for the script with the fixed name and try to load it. If it fails then it moves to a next fixed file name and tries that etc. But it actually works differently by loading all the scripts that it finds and setting `m_listenerScript` to the last one found.

    I've tried to supply my own `slSV3_1aPythonListener.py` file with some callback functions defined. Either my file wasn't loaded / parsed correctly or it's a `PyRun_SimpleFile()` thing which does not override already defined functions (?) In the end my functions weren't called at all.

By hacking the code and making it load explicitly the file I wanted it all worked correctly.

I can fix both issues in the code (and make a PR) but first I'd like to know if I'm correct about the bugs / shortcomings.

**Comment by alaindargelas** [comment]
Please do submit all the changes you mentioned.
The absolute paths to some installation are obsolete and should be removed. Surelog does not install this file anymore. The command line argument was probably not tested at all, please fix it.
The only thing that can still make sense to keep is the local path to the directory.
By the command line should take precedence. 
I think there is one test Surelog/tests/ that uses the path in the local directory.
Thanks!
