### ISSUE TITLE
Forward declare all the UHDM classes in VpiListener.h

### ISSUE THREAD

**Issue by hs-apotell** [alainmarcel/Surelog#355]
To keep compilation times reasonable, references to ```uhdm.h``` should be avoided in client headers. But including ```VpiListener.h``` requires including ```uhdm.h```. Forward declaring all UHDM classes should resolve the issue.

P.S. There is also an inherent header file include order dependency between ```uhdm.h``` and ```VpiListener.h```

**Comment by alaindargelas** [comment]
Fixed by https://github.com/alainmarcel/UHDM/pull/205
Please include uhdm_forward_decl.h where it is needed instead of uhdm.h.
I do not want to have it included by default, as it messes up IDEs for development.
