### ISSUE TITLE
VpiFullName is not access

### ISSUE THREAD

**Issue by bsp13** [alainmarcel/Surelog#405]
We are try to acess VpiFullName() for CurState in module FSM1 in tests/FSMBsp13/dut.v file.

Here, Our code to acess VpiFullName and we got null string.

    UHDM::ref_obj *ref = (UHDM::ref_obj*) condition;
    const UHDM::any* conany = ref->Actual_group() ;
    UHDM::logic_net *logicnet = (UHDM::logic_net*)conany;
    std::cout << logicnet->VpiFullName() << std::endl;

/////////////dut.v///////////////////////////
module FSM1 (Clk, Reset, SlowRam, Read, Write);
input Clk, Reset, SlowRam;
output Read, Write;

reg Read, Write, Wait, Delay;

parameter [3:0] ST_Read = 0, ST_Write = 1, ST_Delay = 2,
                ST_Trx = 3, ST_Hold = 4, ST_Block = 5,
                ST_Wait = 6, ST_Turn = 7, ST_Quit = 8,
                ST_Exit = 9, ST_Done = 10;

reg       [3:0] CurState, NextState;              //VPiFullName for Curstate

**Comment by alaindargelas** [comment]
Correct, that property is not filled-in yet for many objects.
I'll fix that.

**Comment by alaindargelas** [comment]
Fixed
