### ISSUE TITLE
StringUtils::eliminateRelativePath - not what the name implies!

### ISSUE THREAD

**Issue by hs-apotell** [alainmarcel/Surelog#439]
https://github.com/alainmarcel/Surelog/blob/534354d97637364441f6cb17da364d6a8351ac34/src/SourceCompile/Compiler.cpp#L325

The call to `StringUtils::eliminateRelativePath` doesn't return canonical path, as the name implies. Instead, it replaces all relative directory references i.e. '..' with '__'. Doing this in this context here would generate a bad exe path.

**Comment by alaindargelas** [comment]
Yep, that line is non-nonsensical in this context, that function has only one use in the code, must have gotten here with bad cut and paste.
