### ISSUE TITLE
Broken loop logic in SourceCompile/ParseFile.cpp and PreprocessFile.cpp

### ISSUE THREAD

**Issue by hzeller** [alainmarcel/Surelog#53]
In [`ParseFile.cpp`](https://github.com/alainmarcel/Surelog/blob/master/src/SourceCompile/ParseFile.cpp#L157), there is a loop with an unsigned comparison ... which of course is always true:

  ` for (unsigned int i = infos.size() - 1; i >= 0; i--) {...`

.. which will be an infinite loop.

There is a similar case in [`PreprocessFile.cpp`](https://github.com/alainmarcel/Surelog/blob/master/src/SourceCompile/PreprocessFile.cpp#L974)
  `for (unsigned int i = size - 1; i >= 0; i--) {...`

(in general, the logic in [`getFileId()`](https://github.com/alainmarcel/Surelog/blob/master/src/SourceCompile/PreprocessFile.cpp#L963) looks pretty convoluted, as it does exactly the same thing depending if there is 1 or more things in the `m_TranslationVec`. It looks like there was an infinite loop at some time and this was the, uhm, fix...?)

In general, this looks like it might want to use iterators ?
  `for (auto it = thevector.rbegin(), it != thevector.rend(); ++it)`
There are no unit-tests, so it is hard to isolate and test this one.

**Comment by alainmarcel** [comment]
Fixed
