### ISSUE TITLE
Sort test cases in regression testing

### ISSUE THREAD

**Issue by hzeller** [alainmarcel/Surelog#621]
There are a lot of end-2-end tests in the regression test suite these days. Making it easy to find a particular one would be useful, but currently the order of rows is semi-random (when it finished ? inode order it went through the tests ?)

In particular when running the parallel regression testing and the final table is produced at the very end, it would be useful if the rows would be sorted by test name to be able to quickly find them

**Comment by alaindargelas** [comment]
Fixed by #623
