### ISSUE TITLE
id is different for same variables

### ISSUE THREAD

**Issue by bsp13** [alainmarcel/Surelog#749]
```
module fsm_2_always_block (output reg rd, ds,
input go, ws, clk, rst_n);

typedef enum logic [1:0] {IDLE = 1,GNT0 = 2,GNT1 = 3} state;
state curr_state, next_state;

always @(posedge clk or negedge rst_n) begin

if (!rst_n) 
  curr_state <= IDLE;           <<<<<<<<<<<<<< Both statement have different id
else  
  curr_state <= next_state;   <<<<<<<<<<<<<< 
end

endmodule
```

\_ref_obj: (curr_state), id:91, line:12, parID:90
              |vpiName:curr_state
              |vpiFullName:work@fsm_2_always_block.curr_state
              |vpiActual:
              \_enum_var: (curr_state), id:92, line:7, parent:curr_state, parID:91

\_ref_obj: (curr_state), id:104, line:14, parID:103
                |vpiName:curr_state
                |vpiFullName:work@fsm_2_always_block.curr_state
                |vpiActual:
                \_enum_var: (curr_state), id:105, line:7, parent:curr_state, parID:104

**Comment by alaindargelas** [comment]
Fixed by #752
