### ISSUE TITLE
A warning in PythonAPI.cpp

### ISSUE THREAD

**Issue by alainmarcel** [alainmarcel/Surelog#94]
/home/alain/Surelog/src/API/PythonAPI.cpp:204:31: warning: ISO C++ forbids converting a string constant to ‘wchar_t*’ [-Wwrite-strings]
   Py_SetProgramName(L"surelog"); /* optional but recommended */
                               ^

**Comment by hzeller** [comment]
Uh, for some reason `Py_SetProgramName()` does not take a `const wchar_t*` but a `wchar_t*`. Will work around that.

**Comment by hzeller** [comment]
Apparently it was fixed between 3.6 and 3.7

3.6: https://docs.python.org/3.6/c-api/init.html#c.Py_SetProgramName
3.7: https://docs.python.org/3.7/c-api/init.html#c.Py_SetProgramName
